// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUFk6kloHhpMCBdYOV5SvxlTWvU4aPQBU',
    appId: '1:819709725317:web:6a7b280fbf9539fcbc77ec',
    messagingSenderId: '819709725317',
    projectId: 'myplatopal',
    authDomain: 'myplatopal.firebaseapp.com',
    storageBucket: 'myplatopal.firebasestorage.app',
    measurementId: 'G-WGHESE0PJJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_4a_z8WOwywWaNK--sDHkCoazGMdvKG8',
    appId: '1:819709725317:android:91e0f60dca8210e9bc77ec',
    messagingSenderId: '819709725317',
    projectId: 'myplatopal',
    storageBucket: 'myplatopal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgUcKJXzQIxTthmXQl9Ec8kiE6GpIyCV4',
    appId: '1:819709725317:ios:214171651f3139e0bc77ec',
    messagingSenderId: '819709725317',
    projectId: 'myplatopal',
    storageBucket: 'myplatopal.firebasestorage.app',
    iosBundleId: 'com.example.myPlatoPal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgUcKJXzQIxTthmXQl9Ec8kiE6GpIyCV4',
    appId: '1:819709725317:ios:214171651f3139e0bc77ec',
    messagingSenderId: '819709725317',
    projectId: 'myplatopal',
    storageBucket: 'myplatopal.firebasestorage.app',
    iosBundleId: 'com.example.myPlatoPal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUFk6kloHhpMCBdYOV5SvxlTWvU4aPQBU',
    appId: '1:819709725317:web:415b3d3183517554bc77ec',
    messagingSenderId: '819709725317',
    projectId: 'myplatopal',
    authDomain: 'myplatopal.firebaseapp.com',
    storageBucket: 'myplatopal.firebasestorage.app',
    measurementId: 'G-0QL136QL72',
  );
}
